### ISSUE TITLE
Starting docker-compose failed

### ISSUE THREAD

**Issue by dsernahiguita** [RubinLab/epad-dist#25]
I am trying to install epad_lite in my mac:
macOS Catalina version 10.15.7
Docker desktop: version 2.1.0.1

but I got the following error:

_Creating an optimized production build...
_The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ejs@0.1.0 build: `react-scripts --max_old_space_size=4096 build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ejs@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-10-29T19_39_35_676Z-debug.log
ERROR: Service 'myepadjs' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1__

The setup of my epad.yml is:
_host: localhost
mode: lite
config: environment
cache: 
  size: "10g"
  inactivetime: "60m"
compression:
  minsize: "20"
keycloak:
  mode: build
  dockerfiledir: ".\/keycloak"
  user: admin
  password: vivamed123
  email: vivamed@eafit.edu.co
  port: 8899
  loc: "keycloak"
couchdb:
  mode: image
  image: "2.3.1"
  user: admin
  password: admin
  port: 8888
  dblocation: "..\/couchdbloc"
dicomweb:
  mode: build
  dockerfiledir: ".\/dicomweb-server"
  port: 8090
  dbname: chronicle
  log: true
  auth: none
  loc: "pacs"
epadlite:
  mode: build
  dockerfiledir: ".\/epadlite"
  port: 8080
  dbname: epadlite
  log: true
  https: false
  auth: auth
  loc: "api"
epadjs:
  mode: build
  dockerfiledir: ".\/epadjs"
  port: 80
mariadb:
  mode: image
  image: latest
  dbname: epaddb
  user: admin
  password: admin
  rootpassword: admin
  port: 3306
  log: false
  backuploc: ".\/epaddb_nodata.sql"
  dblocation: "..\/mariadbloc"_

The setup of the docker-compose is:version: "3"
services:
  myepadjs:
    build: ./epadjs
    container_name: epad_js
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      - ./epadjs/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./epadjs/entrypoint.sh:/usr/local/bin/entrypoint
    environment:
      REACT_APP_AUTH_URL: "http://localhost/keycloak/auth"
      PUBLIC_URL: "http://localhost"
      REACT_APP_API_URL: "http://localhost/api"
      REACT_APP_WADO_URL: "wadouri:http://localhost/api/wado"
      REACT_APP_BASE_URL: ""
      REACT_APP_AUTH_MODE: ""
      REACT_APP_MODE: "lite"
    depends_on:
      - myepadlite
    networks:
      - epad-network
  mykeycloak:
    build: ./keycloak
    container_name: epad_keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=vivamed123
      - DB_VENDOR=H2
      - PROXY_ADDRESS_FORWARDING=true
    # expose:
    #   - "8899"
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/realm-export.json,/opt/jboss/keycloak/realm-export_epad.json"
    # ports:
    #   - "8899:8080"
    volumes:
      - ./realm-export.json:/opt/jboss/keycloak/realm-export.json
      - ./realm-export_epad.json:/opt/jboss/keycloak/realm-export_epad.json
      - ./terms.ftl:/opt/jboss/keycloak/themes/base/login/terms.ftl
    depends_on:
      - mycouchdb
    networks:
      - epad-network
  mycouchdb:
    image: apache/couchdb:2.3.1
    container_name: epad_couchdb
    # expose:
    #   - "8888"
    # ports:
    #   - "8888:5984"
    volumes:
      - "../couchdbloc:/opt/couchdb/data"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 1m30s
      timeout: 1m
      retries: 10
    depends_on:
      - mymariadb
    networks:
      - epad-network
  mymariadb:
    image: rubinlab/mariadb:latest
    container_name: epad_mariadb
    restart: always
    healthcheck:
      test: "/usr/bin/mysql --user=admin --password=admin --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    # expose:
    #   - "3306"
    # ports:
    #   - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ../mariadbloc:/var/lib/mysql
      - ./epaddb_nodata.sql:/data/application/init.sql
    environment:
      MYSQL_DATABASE: epaddb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - epad-network
  mydicomweb:
    build: ./dicomweb-server
    container_name: epad_dicomweb
    # expose:
    #   - "8090"
    # ports:
    #   - "8090:8090"
    environment:
      DB_SERVER: "http://admin:admin@epad_couchdb"
      DB_NAME: "chronicle"
      AUTH: "none"
      LOGGER: "true"
      PREFIX: "/pacs"
    depends_on:
      - mykeycloak
    healthcheck:
      test: ["CMD", "pm2", "show", "DICOMwebServer"]
      interval: 1m30s
      timeout: 1m
      retries: 10
    networks:
      - epad-network
  myepadlite:
    build: ./epadlite
    container_name: epad_lite
    # expose:
    #   - "8080"
    # ports:
    #   - "8080:8080"
    environment:
      NOSQL_DB_HOST: "http://admin:admin@epad_couchdb"
      NOSQL_DB_NAME: "epadlite"
      LOGGER: "true"
      HTTPS: "false"
      MODE: "lite"
      PREFIX: "api"
      SQL_DB_HOST: "epad_mariadb"
      SQL_DB_NAME: "epaddb"
      SQL_USER: "admin"
      SQL_PASS: "admin"
      SQL_LOGGER: "false"
      AUTH_URL: "http://localhost/keycloak"
      DICOMWEB_BASEURL: "http://epad_dicomweb:8090/pacs"
      AUTH: "auth"
      AUTH_USERINFO_URL: "{epadlite_authuserinfourl}"
    volumes:
      - ../data:/home/node/app/data
    depends_on:
      - mydicomweb
    healthcheck:
      test: ["CMD", "pm2", "show", "ePADlite"]
      interval: 1m30s
      timeout: 1m
      retries: 10
    networks:
      - epad-network
networks:
  epad-network:
    driver: bridge

Thanks in advance
Diana Lucia Serna Higuita

**Comment by emelalkim** [comment]
hi, I suspect the reason build fails is the amount of ram available to the container. epadjs needs 4gb ram to be able to build.
another issue i see with your configuration is you are using localhost as your hostname. unfortunately, you cannot use that as inside the containers localhost resolves to the container itself. you need to use the ip or the shared hostname of the machine. you can enable sharing and use the .local hostname that you see in sharing settings.
you can also use the installation script to get/fix ip. @acavit can give more information about that

**Comment by dsernahiguita** [comment]
Hi, really thank you very much for your prompt response. I was checking the free ram and I have approximately 4.75G free: 
<img width="709" alt="Bildschirmfoto 2020-10-29 um 22 01 23" src="https://user-images.githubusercontent.com/6001712/97632078-4a2bbf00-1a32-11eb-9562-b523d779ca73.png">

so I guess the problem could be the localhost, I had changed the epad.yml to use 127.0.0.1 (instead localhost), but still when I try to run the docker compose I got the same issue

1. Could you please let me know where I can find the installation script to get/fix ip and how can I use it?

epad.yml:
host: 127.0.0.1
mode: lite
config: environment
cache: 
  size: "10g"
  inactivetime: "60m"
compression:
  minsize: "20"
keycloak:
  mode: build
  dockerfiledir: ".\/keycloak"
  user: admin
  password: vivamed123
  email: vivamed@eafit.edu.co
  port: 8899
  loc: "keycloak"
couchdb:
  mode: image
  image: "2.3.1"
  user: admin
  password: admin
  port: 8888
  dblocation: "..\/couchdbloc"
dicomweb:
  mode: build
  dockerfiledir: ".\/dicomweb-server"
  port: 8090
  dbname: chronicle
  log: true
  auth: none
  loc: "pacs"
epadlite:
  mode: build
  dockerfiledir: ".\/epadlite"
  port: 8080
  dbname: epadlite
  log: true
  https: false
  auth: auth
  loc: "api"
epadjs:
  mode: build
  dockerfiledir: ".\/epadjs"
  port: 80
mariadb:
  mode: image
  image: latest
  dbname: epaddb
  user: admin
  password: admin
  rootpassword: admin
  port: 3306
  log: false
  backuploc: ".\/epaddb_nodata.sql"
  dblocation: "..\/mariadbloc"

**Comment by dsernahiguita** [comment]
Hi :)
I found the issue, I had extended the ram to 4G in docker settings and now the instalation is successfully...
maybe you can add this information to the Readme

thanks a lot for your help

Diana
