### ISSUE TITLE
Error 401 "Unauthorized" from epad lite 

### ISSUE THREAD

**Issue by albeporta** [RubinLab/epad-dist#29]
good morning,
i have installed epadlite using epad_manage script (v.0.4) - thick mode on a linux centos 7 - 64bit (as a virtualbox guest that is running on windows 10)

Installation is OK but when i try to access epad from browser, after login (admin/admin), i get a lot of error 401.

I get some logs from container epad_lite and i see this:

{"level":50,"time":1606146608856,"pid":17,"hostname":"c7468b0bfec3","reqId":1,"req":{"method":"GET","url":"/api/users/admin","hostname":"192.168.202.93","remoteAddress":"172.20.0.7","remotePort":59732},"res":{"statusCode":500},"err":{"type":"UnauthenticatedError","message":"Verifying token and getting userinfo: connect EHOSTUNREACH 192.168.202.93:80","stack":"UnauthenticatedError: Verifying token and getting userinfo: connect EHOSTUNREACH 192.168.202.93:80\n    at Object.authCheck (/home/node/app/plugins/Other.js:1512:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Object.auth (/home/node/app/plugins/Other.js:1653:24)","name":"UnauthenticatedError","data":{"message":"Verifying token and getting userinfo: connect EHOSTUNREACH 192.168.202.93:80"}},"msg":"Verifying token and getting userinfo: connect EHOSTUNREACH 192.168.202.93:80","v":1}
{"level":50,"time":1606146608858,"pid":17,"hostname":"c7468b0bfec3","msg":"Cannot notify user Cannot read property 'username' of undefined","v":1}
{"level":30,"time":1606146608863,"pid":17,"hostname":"c7468b0bfec3","reqId":1,"res":{"statusCode":401},"responseTime":1018.1098389998078,"msg":"request completed","v":1}
{"level":50,"time":1606146608864,"pid":17,"hostname":"c7468b0bfec3","reqId":2,"req":{"method":"GET","url":"/api/projects","hostname":"192.168.202.93","remoteAddress":"172.20.0.7","remotePort":59734},"res":{"statusCode":500},"err":{"type":"UnauthenticatedError","message":"Verifying token and getting userinfo: connect EHOSTUNREACH 192.168.202.93:80","stack":"UnauthenticatedError: Verifying token and getting userinfo: connect EHOSTUNREACH 192.168.202.93:80\n    at Object.authCheck (/home/node/app/plugins/Other.js:1512:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Object.auth (/home/node/app/plugins/Other.js:1653:24)","name":"UnauthenticatedError","data":{"message":"Verifying token and getting userinfo: connect EHOSTUNREACH 192.168.202.93:80"}},"msg":"Verifying token and getting userinfo: connect EHOSTUNREACH 192.168.202.93:80","v":1}
{"level":50,"time":1606146608864,"pid":17,"hostname":"c7468b0bfec3","msg":"Cannot notify user Cannot read property 'username' of undefined","v":1}
{"level":30,"time":1606146608865,"pid":17,"hostname":"c7468b0bfec3","reqId":2,"res":{"statusCode":401},"responseTime":1011.1660169996321,"msg":"request completed","v":1}
{"level":50,"time":1606146608866,"pid":17,"hostname":"c7468b0bfec3","reqId":3,"req":{"method":"GET","url":"/api/projects/lite/subjects","hostname":"192.168.202.93","remoteAddress":"172.20.0.7","remotePort":59736},"res":{"statusCode":500},"err":{"type":"UnauthenticatedError","message":"Verifying token and getting userinfo: connect EHOSTUNREACH 192.168.202.93:80","stack":"UnauthenticatedError: Verifying token and getting userinfo: connect EHOSTUNREACH 192.168.202.93:80\n    at Object.authCheck (/home/node/app/plugins/Other.js:1512:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Object.auth (/home/node/app/plugins/Other.js:1653:24)","name":"UnauthenticatedError","data":{"message":"Verifying token and getting userinfo: connect EHOSTUNREACH 192.168.202.93:80"}},"msg":"Verifying token and getting userinfo: connect EHOSTUNREACH 192.168.202.93:80","v":1}
{"level":50,"time":1606146608867,"pid":17,"hostname":"c7468b0bfec3","msg":"Cannot notify user Cannot read property 'username' of undefined","v":1}
{"level":30,"time":1606146608868,"pid":17,"hostname":"c7468b0bfec3","msg":"Checking hasAccessToProject for url: /api/projects/lite/subjects and project lite","v":1}
{"level":30,"time":1606146608870,"pid":17,"hostname":"c7468b0bfec3","reqId":3,"res":{"statusCode":401},"responseTime":1013.8001390001737,"msg":"request completed","v":1}
warning: please use IANA standard timezone format ('Etc/GMT0')
{"level":30,"time":1606146608878,"pid":17,"hostname":"c7468b0bfec3","reqId":4,"req":{"method":"GET","url":"/api/notifications","hostname":"192.168.202.93","remoteAddress":"172.20.0.7","remotePort":59744},"msg":"incoming request","v":1}

192.168.202.93 is centos 7 IP.
Could you help me to resolve this problem ?

thanks
bye Alberto

**Comment by acavit** [comment]
Hi Alberto. It looks like your ip is not reachable. Are you browsing ePad
from a browser on your Windows machine ? or You are trying with a browser
in your Centos7 virtual machine ? Other thing is you don't need to add port
80 at the end of the ip when you are putting it during the installation
unless you set up a different port than 80.
Thanks

**Comment by albeporta** [comment]
goodmorning,
the connection problem is related a firewalld problem on centos 7 and docker.
It's a known issue and i don't find a working workaround.
Now i stopped firewald after epad lite and all works fine.

bye ALberto

**Comment by acavit** [comment]
Hi ALberto thank you very much for your input. Interesting that we are
using Centos machines too but ours is not in a virtual environment. One
detail that I would like to ask. After starting ePad, which machine's
browser do you use? A browser in windows (your host) or a browser in the
virtual machine (centos) ?
Thanks

**Comment by albeporta** [comment]
hi acavit,
i'm using a virtualized centos 7 from a window 10 host (we are using virtualbox as hypervisor) and
i access epadlite from window 10 host
The problem with firewalld was resolved using with command to open http port:
sudo firewall-cmd --zone=public --add-service=http --permanent

In this way epadlite is working fine.
Thanks for your support

bye Alberto

**Comment by acavit** [comment]
Hi Alberto thank you very much I understand now.
